#####
name: USGan
noise_level: 0  #  noise level
port: 6019   #  port parameters
save_root: './output/Cyc/NC+R/'
image_save: './output/Cyc/NC+R/img/'

# lamda weight
Adv_lamda: 1
Cyc_lamda: 10
idt_lamda: 1  # 0.5*10
Corr_lamda: 10
Smooth_lamda: 5
Progressive_lamda: 10

epoch: 0        # starting epoch
n_epochs: 200       # How often do you want to display output images during training
batchSize: 1               # size of the batches
dataroot: 'data/train/'     # root directory of the dataset
val_dataroot: 'data/val/'
test_dataroot: 'data/test/'
lr: 0.0002                   # initial learning rate
decay_epoch: 20            # epoch to start linearly decaying the learning rate to 0
size: 256                # size of the data crop
input_nc: 1         
output_nc: 1                  
cuda: True                
n_cpu: 1

